# Build Stage
FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements.txt .
COPY basic-app.py .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# Runtime Stage
FROM `
WORKDIR /app
COPY --from=builder /install /install
COPY --from=builder /app .
ENV PYTHONPATH=/install/lib/python3.11/site-packages
CMD ["basic-app.py"]