FROM ubuntu:latest
WORKDIR /app
COPY . .
COPY requirements.txt /app/
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv
RUN python3 -m venv venv && \
    source venv/bin/activate && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
CMD ["/app/venv/bin/python3", "flask-app.py"]