# Build Stage
FROM golang:1.22 AS builder
WORKDIR /app
COPY demo-api.go .
RUN go build -o demo-api demo-api.go
RUN CGO_ENABLED=0 GOOS=linux go build -o demo-api demo-api.go

# Runtime Stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/demo-api .
EXPOSE 8080
CMD ["./demo-api"]
