import sys
import os

# --- FIX: Add the project directory to the Python path ---
# This allows Airflow to see the sibling folders (quality, transformation, metadata)
PROJECT_PATH = "/workspaces/the-data-stack-lab/lakefs_labs/sports_broadcast_analysis"
sys.path.append(PROJECT_PATH)
# ---------------------------------------------------------

from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime

import polars as pl

# Now these imports will work because the directory is in the path
from lakefs_client import (
    compare_branches,
    create_branch,
    download_object,
    merge_branches,
    upload_object,
    commit as lakefs_commit
)

from quality.validity import validate_broadcasts
from transformation.clean import clean_broadcasts
from transformation.parquet import write_parquet
from transformation.aggregate import aggregate_broadcasts
from metadata.metadata import write_commit_metadata

def hello_airflow():
    print("Hello Airflow!")

def create_feature_branch():
    return create_branch("lakefs-tutorial", "main", "feature-summary")

def download():
    return download_object(
        repo="lakefs-tutorial",
        branch="main",
        object_path="sb_dataset_v3.csv",
        destination="data/raw/sb_dataset_v3.csv"
    )

def validate(local_csv):
    if not os.path.exists(local_csv):
        raise FileNotFoundError(local_csv)
    if os.path.getsize(local_csv) == 0:
        raise ValueError("Downloaded CSV is empty")
    df = pl.read_csv(local_csv)
    df = clean_broadcasts(df)
    df = validate_broadcasts(df)
    if df.height == 0:
        raise ValueError("No valid rows remain")
    cleaned_path = "data/intermediate/sb_dataset_v3_clean.csv"
    os.makedirs("data/intermediate", exist_ok=True)
    df.write_csv(cleaned_path)
    return cleaned_path

def aggregate(cleaned_path):
    df = pl.read_csv(cleaned_path)
    summary = aggregate_broadcasts(df)
    output_path = "data/processed/sb_dataset_v3_summary.parquet"
    os.makedirs("data/processed", exist_ok=True)
    write_parquet(summary, output_path)
    if not os.path.exists(output_path):
        raise FileNotFoundError(f"Expected parquet output not created: {output_path}")
    return output_path

def upload(branch, parquet_path):
    with open(parquet_path, "rb") as f:
        file_content = f.read()
    upload_object(
        repo="lakefs-tutorial",
        branch=branch,
        object_path="sb_dataset_v3_summary.parquet",
        file_content=file_content
    )
    return True

def compare(branch):
    comparison = compare_branches(
        repo="lakefs-tutorial",
        source_branch=branch,
        destination_branch="main"
    )
    diff_results = comparison.get("results", [])
    diff_types = {item.get("type") for item in diff_results if isinstance(item, dict)}
    print("Diff types:", diff_types)
    return list(diff_types)

def commit_changes(branch):
    commit_operation = lakefs_commit(
        repo="lakefs-tutorial",
        branch=branch,
        message="Sports broadcast summary generated by Airflow"
    )
    if commit_operation:
        commit_id = commit_operation["id"]
        commit_message = commit_operation["message"]
        write_commit_metadata(commit_id, commit_message, branch)
        return commit_id
    raise ValueError("Commit failed")

def merge(branch):
    merge_branches(
        repo="lakefs-tutorial",
        source_branch=branch,
        destination_branch="main"
    )
    return True

with DAG(
    dag_id="sports_broadcast_analysis",
    start_date=datetime(2026, 6, 6),
    schedule="0 */2 * * *",
    catchup=False
) as dag:

    task1 = PythonOperator(task_id="hello_airflow", python_callable=hello_airflow)
    task2 = PythonOperator(task_id="branch", python_callable=create_feature_branch)
    task3 = PythonOperator(task_id="download", python_callable=download)
    task4 = PythonOperator(
        task_id="validate", 
        python_callable=validate,
        op_kwargs={"local_csv": "{{ ti.xcom_pull(task_ids='download') }}"}
    )
    task5 = PythonOperator(
        task_id="aggregate", 
        python_callable=aggregate,
        op_kwargs={"cleaned_path": "{{ ti.xcom_pull(task_ids='validate') }}"}
    )
    task6 = PythonOperator(
        task_id="upload", 
        python_callable=upload,
        op_kwargs={
            "branch": "{{ ti.xcom_pull(task_ids='branch') }}",
            "parquet_path": "{{ ti.xcom_pull(task_ids='aggregate') }}"
        }
    )
    task7 = PythonOperator(
        task_id="compare", 
        python_callable=compare,
        op_kwargs={"branch": "{{ ti.xcom_pull(task_ids='branch') }}"}
    )
    task8 = PythonOperator(
        task_id="commit", 
        python_callable=commit_changes,
        op_kwargs={"branch": "{{ ti.xcom_pull(task_ids='branch') }}"}
    )
    task9 = PythonOperator(
        task_id="merge", 
        python_callable=merge,
        op_kwargs={"branch": "{{ ti.xcom_pull(task_ids='branch') }}"}
    )

    (task1 >> task2 >> task3 >> task4 >> task5 >> task6 >> task7 >> task8 >> task9)
