from prometheus_client import Counter, Gauge, Histogram

TASK_NAMES = (
	"tasks.math.add",
	"tasks.math.mul",
	"tasks.math.square",
	"tasks.delay.delay_task",
	"tasks.etl.ingestion_task",
	"tasks.etl.transformation_task",
	"tasks.etl.loading_task",
	"tasks.etl.daily_etl_pipeline",
	"tasks.retries.retry_task",
	"tasks.logger.log_task",
	"tasks.heartbeat.heartbeat_task",
	"tasks.heartbeat.cron_task",
)

QUEUE_NAMES = (
	"default",
	"math_task_queue",
	"delayed_task_queue",
	"etl_queue",
	"retry_task_queue",
	"log_task_queue",
)

tasks_total = Counter(
	"celery_tasks_total",
	"Total number of Celery tasks executed",
	["task_name"],
)

tasks_failed_total = Counter(
	"celery_tasks_failed_total",
	"Total number of failed Celery tasks",
	["task_name"],
)

tasks_duration_seconds = Histogram(
	"celery_tasks_duration_seconds",
	"Duration of Celery tasks in seconds",
	["task_name"],
	buckets=[0.1, 0.5, 1, 2, 5, 10, 30, 60],
)

tasks_last_run_timestamp = Gauge(
	"celery_tasks_last_run_timestamp",
	"Timestamp of the last run of each Celery task",
	["task_name"],
)

queue_length = Gauge(
	"celery_queue_length",
	"Current length of Celery queues",
	["queue_name"],
)

active_workers = Gauge(
	"celery_active_workers",
	"Number of active Celery workers",
	["worker_name"],
)

etl_records_processed = Counter(
	"celery_etl_records_processed_total",
	"Total number of records processed by ETL tasks",
	["task_name", "status"],
)

etl_duration_seconds = Histogram(
	"celery_etl_duration_seconds",
	"Duration of ETL tasks in seconds",
	["task_name"],
	buckets=[1, 5, 10, 30, 60, 120, 300],
)

retry_attempts_total = Counter(
	"celery_retry_attempts_total",
	"Total number of retry attempts for tasks",
	["task_name"],
)

log_messages_total = Counter(
	"celery_log_messages_total",
	"Total number of log messages generated by tasks",
	["task_name", "log_level"],
)

log_message_length = Histogram(
	"celery_log_message_length",
	"Length of log messages generated by tasks",
	["task_name", "log_level"],
	buckets=[10, 50, 100, 200, 500, 1000],
)