[sources.sql_database.credentials]
drivername = "postgresql+psycopg2"
database = "neondb"
password = "npg_eVF43HAEKIfr"
username = "neondb_owner"
host = "ep-silent-poetry-a1ujigrh-pooler.ap-southeast-1.aws.neon.tech"
port = 5432
