name: 'dbt_project_tutorial'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

models:
  dbt_project_tutorial:
    
    staging:
      +schema: staging
      +tags: ['staging']
      +materialized: table

    intermediate:
      +schema: intermediate
      +tags: ['intermediate']
      +materialized: table

    marts:
      +schema: marts
      +tags: ['marts']
      +materialized: view

seeds:
  dbt_project_tutorial:
    payment_method_desc:
      +schema: lookup_tables
      +tags: ['lookup', 'seed', 'payment_methods']      
      +column_types:
        payment_method: varchar
        description: varchar
    employee_workspace_country:
      +schema: lookup_tables
      +tags: ['lookup', 'seed', 'employee_workspace_country']      
      +column_types:
        employee_id: varchar
        first_name: varchar
        last_name: varchar
        company: varchar
        department: varchar
        workspace_country: varchar
        updated_at: timestamp