dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /data/analytics.duckdb
      schema: dev
      threads: 4


    prod:
      type: duckdb
      path: /data/analytics.duckdb
      schema: prod
      threads: 8

