name: dbt CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt_labs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt and adapter
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-duckdb

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_project:
            target: dev
            outputs:
              dev:
                type: duckdb
                path: ./duckdb_data/analytics.duckdb
                schema: dev
                threads: 4
          EOF

      - name: Install dbt packages
        run: dbt deps

      - name: Seed data
        run: dbt seed

      - name: Run snapshots
        run: dbt snapshot

      - name: Build project
        run: dbt build